# List of Debian packages used to build MATE Desktop
# on my Ubuntu system. Some of them may not be necessary.
# Tested with:
# - Ubuntu 26.04 daily-live image 2026-04-18 - running on virtualbox 7.2.6

build-essential
intltool
libglib2.0-dev
libglib2.0-bin
libgtk-3-dev
libgtop2-dev
libcanberra-gtk3-dev
exempi
gobject-introspection
libnotify-dev
libexif-dev
gvfs
libsecret-1-dev
gnome-keyring
dbus
libcairo2-dev
libxrandr-dev
libcanberra-dev
upower
autopoint
yelp-tools
libmpfr-dev
libmpc-dev
python-dbus-dev
libvte-2.91-dev
wcm
libwnck-3-dev
libgdk-pixbuf-2.0-dev
shared-mime-info
pkexec
libselinux-dev
python-gi-dev
libgail-3-dev
